spring.application.name=api-gateway
server.port=8080

# Eureka
eureka.client.service-url.defaultZone=https://eureka-server-1x0q.onrender.com/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=api-gateway-hospital.onrender.com
eureka.instance.non-secure-port=443
eureka.instance.non-secure-port-enabled=true
eureka.instance.secure-port-enabled=false

# Routes - using direct URLs instead of lb://
spring.cloud.gateway.mvc.routes[0].id=auth-service
spring.cloud.gateway.mvc.routes[0].uri=https://auth-service-hospital.onrender.com
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.mvc.routes[1].id=patient-service
spring.cloud.gateway.mvc.routes[1].uri=https://patient-service-hospital.onrender.com
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/api/patients/**

spring.cloud.gateway.mvc.routes[2].id=doctor-service
spring.cloud.gateway.mvc.routes[2].uri=https://doctor-service-hospital.onrender.com
spring.cloud.gateway.mvc.routes[2].predicates[0]=Path=/api/doctors/**

spring.cloud.gateway.mvc.routes[3].id=appointment-service
spring.cloud.gateway.mvc.routes[3].uri=https://appointment-service-hospital.onrender.com
spring.cloud.gateway.mvc.routes[3].predicates[0]=Path=/api/appointments/**

# CORS
spring.cloud.gateway.mvc.globalcors.cors-configurations.[/**].allowed-origins=*
spring.cloud.gateway.mvc.globalcors.cors-configurations.[/**].allowed-methods=*
spring.cloud.gateway.mvc.globalcors.cors-configurations.[/**].allowed-headers=*